const CONTAINER_ID = "chart"
const ATTR_SANKEY_LINK = "data-sankey-link"
const ATTR_SANKEY_NODE = "data-sankey-node"
const TRANSITION_DURATION = 500

export { ATTR_SANKEY_LINK, ATTR_SANKEY_NODE, CONTAINER_ID, TRANSITION_DURATION }
