declare const styles: {
  readonly "backHome": string
  readonly "bullet": string
  readonly "codeFragment": string
  readonly "codeFragmentButton": string
  readonly "d3js": string
  readonly "dataList": string
  readonly "demoName": string
  readonly "demoTitle": string
  readonly "demoWip": string
  readonly "demosLegend": string
  readonly "demosLists": string
  readonly "divisor": string
  readonly "fileNameWrapper": string
  readonly "footer": string
  readonly "ghButtons": string
  readonly "highlightStorybook": string
  readonly "highlightTesting": string
  readonly "homeDemoNameLink": string
  readonly "homeDemoNumber": string
  readonly "mainSource": string
  readonly "notes": string
  readonly "pageHeader": string
  readonly "raphael": string
  readonly "rootLayout": string
  readonly "rowWrapper": string
  readonly "sourceNumber": string
  readonly "sourcesList": string
  readonly "storybook": string
  readonly "tag": string
  readonly "tagCollection": string
  readonly "testing": string
}
export = styles
